namespace CoreFramework.ScriptableObjectArchitecture.ScriptableObjectVariables
{
    public enum VariableTypes
    {
        AnimationCurve,
        AudioClip,
        Bool,
        Bounds,
        Byte,
        Char,
        Color32,
        Color,
        Double,
        Float,
        GameObject,
        Int,
        LayerMask,
        Long,
        Object,
        Quaternion,
        SByte,
        Scene,
        Short,
        String,
        UInt,
        ULong,
        UShort,
        Vector2,
        Vector3,
        Vector4
    }
}